services:
    postgres:
      image: postgres
      ports:
        - "5433:5432"
      expose:
        - "5432"
      environment:
         POSTGRES_USER: ${DB_USERNAME}
         POSTGRES_PASSWORD: ${DB_PASSWORD}
         POSTGRES_DB: ${DB_NAME}